# Generated by Django 5.2.7 on 2026-03-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CancionActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('artista', models.CharField(max_length=200)),
                ('album', models.CharField(blank=True, max_length=200)),
                ('duracion', models.DurationField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='canciones/')),
            ],
            options={
                'verbose_name': 'Canción Actual',
                'verbose_name_plural': 'Canciones Actuales',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EstacionRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Tu Radio', max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('stream_url', models.URLField(help_text='URL del streaming de la radio', max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='radio/')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estación de Radio',
                'verbose_name_plural': 'Estaciones de Radio',
            },
        ),
        migrations.CreateModel(
            name='OyenteActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('fecha_conexion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
                ('esta_escuchando', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Oyente Activo',
                'verbose_name_plural': 'Oyentes Activos',
            },
        ),
        migrations.CreateModel(
            name='EstadisticaRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('oyentes_maximos_simultaneos', models.PositiveIntegerField(default=0)),
                ('total_conexiones', models.PositiveIntegerField(default=0)),
                ('tiempo_promedio_escucha', models.DurationField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estadística de Radio',
                'verbose_name_plural': 'Estadísticas de Radio',
                'ordering': ['-fecha'],
                'unique_together': {('fecha',)},
            },
        ),
    ]
