# Generated by Django 5.2.7 on 2026-03-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CancionActual',
        ),
    ]
