# Generated by Django 5.2.7 on 2026-03-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_delete_cancionactual'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150)),
                ('mensaje', models.TextField(max_length=500)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
