# Generated by Django 5.2.7 on 2026-03-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_mensajechat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertenciaChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('advertido_por', models.CharField(blank=True, help_text='Usuario admin que dio la advertencia', max_length=150)),
                ('razon', models.TextField(help_text='Razón de la advertencia')),
                ('mensaje_original', models.TextField(blank=True, help_text='Mensaje que causó la advertencia')),
                ('fecha_advertencia', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False, help_text='Si el usuario la ha visto')),
            ],
            options={
                'verbose_name': 'Advertencia de Chat',
                'verbose_name_plural': 'Advertencias de Chat',
                'ordering': ['-fecha_advertencia'],
            },
        ),
        migrations.CreateModel(
            name='ModeracionChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('bloqueo', 'Bloqueo de Usuario'), ('desbloqueo', 'Desbloqueo de Usuario'), ('advertencia', 'Advertencia'), ('eliminacion', 'Eliminación de Mensaje'), ('desbloqueo_manual', 'Desbloqueo Manual')], max_length=20)),
                ('username_objetivo', models.CharField(help_text='Usuario afectado por la acción', max_length=150)),
                ('moderador', models.CharField(help_text='Usuario admin que realizó la acción', max_length=150)),
                ('mensaje_id', models.IntegerField(blank=True, help_text='ID del mensaje eliminado (si aplica)', null=True)),
                ('contenido_mensaje', models.TextField(blank=True, help_text='Contenido del mensaje eliminado (si aplica)')),
                ('razon', models.TextField(blank=True, help_text='Razón de la acción')),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('ip_moderador', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Acción de Moderación',
                'verbose_name_plural': 'Acciones de Moderación',
                'ordering': ['-fecha_accion'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioBloqueadoChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('bloqueado_por', models.CharField(blank=True, help_text='Usuario admin que bloqueó', max_length=150)),
                ('razon', models.TextField(blank=True, help_text='Razón del bloqueo')),
                ('fecha_bloqueo', models.DateTimeField(auto_now_add=True)),
                ('fecha_desbloqueo', models.DateTimeField(blank=True, help_text='Fecha de desbloqueo automático (opcional)', null=True)),
                ('permanente', models.BooleanField(default=True, help_text='Bloqueo permanente o temporal')),
                ('activo', models.BooleanField(default=True, help_text='Si el bloqueo está activo')),
            ],
            options={
                'verbose_name': 'Usuario Bloqueado del Chat',
                'verbose_name_plural': 'Usuarios Bloqueados del Chat',
                'ordering': ['-fecha_bloqueo'],
            },
        ),
    ]
