# Generated by Django 5.2.7 on 2026-03-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_advertenciachat_moderacionchat_usuariobloqueadochat'),
    ]

    operations = [
        migrations.AddField(
            model_name='oyenteactivo',
            name='usuario',
            field=models.CharField(blank=True, help_text='Nombre de usuario si está autenticado', max_length=150, null=True),
        ),
    ]
