# Generated by Django 5.2.7 on 2026-03-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0005_oyenteactivo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioBloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Nombre de usuario bloqueado', max_length=150, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP opcional del usuario', null=True)),
                ('fecha_bloqueo', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, help_text='Fecha de desbloqueo automático (opcional)', null=True)),
                ('bloqueado_por', models.CharField(help_text='Administrador que realizó el bloqueo', max_length=150)),
                ('activo', models.BooleanField(default=True, help_text='Si el bloqueo está activo')),
                ('tipo_accion', models.CharField(choices=[('bloqueo', 'Bloqueo de Usuario'), ('desbloqueo', 'Desbloqueo de Usuario'), ('advertencia', 'Advertencia'), ('eliminacion', 'Eliminación de Mensaje'), ('desbloqueo_manual', 'Desbloqueo Manual')], max_length=20)),
                ('username_objetivo', models.CharField(help_text='Usuario afectado por la acción', max_length=150)),
                ('moderador', models.CharField(help_text='Usuario admin que realizó la acción', max_length=150)),
                ('mensaje_id', models.IntegerField(blank=True, help_text='ID del mensaje eliminado (si aplica)', null=True)),
                ('contenido_mensaje', models.TextField(blank=True, help_text='Contenido del mensaje eliminado (si aplica)')),
                ('razon', models.TextField(blank=True, help_text='Razón de la acción')),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('ip_moderador', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Acción de Moderación',
                'verbose_name_plural': 'Acciones de Moderación',
                'ordering': ['-fecha_accion'],
            },
        ),
        migrations.DeleteModel(
            name='ModeracionChat',
        ),
    ]
